/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projectstore.view;

import com.model.seller.SellerDAO;
import com.model.seller.SellerDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author STU-03
 */
public class SellerInsertGUI extends javax.swing.JFrame implements ActionListener {

    private String selId;
    private SellerDAO dao = new SellerDAO();
    private SellerGUI seller = null;
    private boolean IdCheck = false;

    /**
     * Creates new form CustomerInsert
     */
    public SellerInsertGUI() {
        initComponents();
        init(); // insert 부터 시작!!
        addEvent();
    }

    SellerInsertGUI(SellerGUI seller) {
        this();
        this.seller = seller;
    }

    SellerInsertGUI(String selId, boolean state, SellerGUI seller) {
        this();
        this.selId = selId;
        this.seller = seller;
        try {
            if (state) {
                detailSearch();
                updateTextSet();
                setTitle("판매원 정보 수정");
            } else {
                detailSearch();
                detailTextSet();
                setTitle("판매원 상세정보");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTel2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfZipcode = new javax.swing.JTextField();
        btAddress = new javax.swing.JButton();
        tfAddress1 = new javax.swing.JTextField();
        tfAddress2 = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btCancle = new javax.swing.JButton();
        tfGender = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btDup = new javax.swing.JButton();
        tfTel1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfJumin1 = new javax.swing.JTextField();
        tfJumin2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPwd = new javax.swing.JPasswordField();
        tfPwdCheck = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("판매원 등록");
        setResizable(false);

        jLabel1.setText("아이디");

        jLabel2.setText("이름");

        jLabel3.setText("핸드폰 번호");

        jLabel4.setText("주민번호");

        jLabel5.setText("성별");

        btAddress.setText("주소검색");

        btAdd.setText("등록");

        btCancle.setText("닫기");

        jLabel6.setText("우편번호");

        btDup.setText("중복검사");

        jLabel7.setText(" - ");

        cbTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "010", "011", "070" }));

        jLabel8.setText(" - ");

        jLabel12.setText("주소");

        jLabel13.setText("나머지 주소");

        jLabel14.setText("비밀번호");

        jLabel10.setText("-");

        jLabel15.setText("비밀번호 확인");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfAddress1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAddress))
                            .addComponent(tfAddress2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfJumin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfJumin2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfTel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btDup)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPwdCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDup, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfPwdCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJumin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJumin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdd)
                    .addComponent(btCancle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerInsertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerInsertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerInsertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerInsertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerInsertGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btAddress;
    private javax.swing.JButton btCancle;
    private javax.swing.JButton btDup;
    private javax.swing.JComboBox<String> cbTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField tfAddress1;
    private javax.swing.JTextField tfAddress2;
    private javax.swing.JTextField tfGender;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJumin1;
    private javax.swing.JTextField tfJumin2;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPwd;
    private javax.swing.JPasswordField tfPwdCheck;
    private javax.swing.JTextField tfTel1;
    private javax.swing.JTextField tfTel2;
    public javax.swing.JTextField tfZipcode;
    // End of variables declaration//GEN-END:variables

    private void init() {

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        btAdd.setText("등록");
    }

    private void addEvent() {
        btCancle.addActionListener(this);
        btAdd.addActionListener(this);
        btAddress.addActionListener(this);
        btDup.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btCancle) {
            dispose();
        } else if (e.getSource() == btAddress) {
            SubZipcode s = new SubZipcode(this);
            s.setVisible(true);
        } else if (e.getSource() == btAdd) {
            if (btAdd.getText().equals("수정")) {
                try {
                    update();
                    dispose();
                    seller.sellerSelectAll();
                    seller.panmaeSelectAll();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            } else if (btAdd.getText().equals("등록")) {
                try {
                    insert();
                    seller.sellerSelectAll();
                    seller.panmaeSelectAll();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        } else if (e.getSource() == btDup) {
            try {
                idDup();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    private void detailTextSet() {
        tfAddress1.setEditable(false);
        tfAddress2.setEditable(false);
        tfGender.setEditable(false);
        tfId.setEditable(false);
        tfName.setEditable(false);
        tfTel1.setEditable(false);
        tfTel2.setEditable(false);
        tfZipcode.setEditable(false);
        tfPwdCheck.setEditable(false);

        cbTel.setEnabled(false);

        btAddress.setEnabled(false);
        btDup.setEnabled(false);
        btAdd.setEnabled(false);
    }

    private void detailSearch() throws SQLException {
        SellerDTO dto = dao.selectById(selId);
        tfId.setText(selId);
        tfPwd.setText(dto.getSeller_pwd());
        tfName.setText(dto.getSeller_name());
        tfGender.setText(dto.getSeller_gender());
        tfZipcode.setText(dto.getZipcode());
        tfAddress1.setText(dto.getAddress1());
        tfAddress2.setText(dto.getAddress2());

        String tel = dto.getSeller_hp();
        if (tel != null && !tel.isEmpty()) {
            String tel1 = tel.substring(0, tel.indexOf("-"));
            String tel2 = tel.substring(tel.indexOf("-") + 1, tel.lastIndexOf("-"));
            String tel3 = tel.substring(tel.lastIndexOf("-") + 1);

            cbTel.setSelectedItem(tel1);
            tfTel1.setText(tel2);
            tfTel2.setText(tel3);
        }

        String jumin = dto.getSeller_jumin();
        if (jumin != null && !jumin.isEmpty()) {
            String jumin1 = jumin.substring(0, jumin.indexOf("-"));
            String jumin2 = jumin.substring(jumin.lastIndexOf("-") + 1);

            tfJumin1.setText(jumin1);
            tfJumin2.setText(jumin2);
        }

    }

    private void updateTextSet() {
        btAdd.setText("수정");
        tfId.setEditable(false);
        tfName.setEditable(false);
        tfGender.setEditable(false);
        tfJumin1.setEditable(false);
        tfJumin2.setEditable(false);

        btDup.setEnabled(false);
    }

    private void update() throws SQLException {
        String tel1 = (String) cbTel.getSelectedItem();
        String tel2 = tfTel1.getText();
        String tel3 = tfTel2.getText();

        String tel = "";
        if (tel2 != null && !tel2.isEmpty()) {
            if (tel3 != null && !tel3.isEmpty()) {
                tel = tel1 + "-" + tel2 + "-" + tel3;
            }
        }
        SellerDTO dto = new SellerDTO();
        dto.setSeller_id(tfId.getText());

        dto.setZipcode(tfZipcode.getText());
        dto.setAddress1(tfAddress1.getText());
        dto.setAddress2(tfAddress2.getText());

        dto.setSeller_hp(tel);

        String pwd = tfPwd.getText();
        String pwdCheck = tfPwdCheck.getText();
        if (pwd == null || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호를 입력하셔야 합니다.");
        }
        
        if (pwdCheck == null || pwdCheck.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호 확인을 하셔야 합니다.");
            tfPwdCheck.requestFocus();
            return;
        }
        
        if(!pwd.equals(pwdCheck)){
            JOptionPane.showMessageDialog(this, "입력하신 비밀번호가 일치하지 않습니다.");
            tfPwdCheck.requestFocus();
            return;
        }
        dto.setSeller_pwd(pwd);

        int n = dao.update(dto);
        if (n > 0) {
            JOptionPane.showMessageDialog(this, "수정완료!");
        } else {
            JOptionPane.showMessageDialog(this, "수정실패!");
        }
    }

    private void insert() throws SQLException {
        SellerDTO dto = new SellerDTO();

        String tel1 = (String) cbTel.getSelectedItem();
        String tel2 = tfTel1.getText();
        String tel3 = tfTel2.getText();

        String tel = "";
        if (tel2 != null && !tel2.isEmpty()) {
            if (tel3 != null && !tel3.isEmpty()) {
                tel = tel1 + "-" + tel2 + "-" + tel3;
            }
        }
        
        String pwd = tfPwd.getText();
        String pwdCheck = tfPwdCheck.getText();

        if (!IdCheck) {
            JOptionPane.showMessageDialog(this, "아이디 중복체크를 해야 합니다.");
            tfId.requestFocus();
            return;
        }

        String name = tfName.getText();

        if (name == null || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "이름을 입력해야 합니다.");
            tfName.requestFocus();
            return;
        }
        String id = tfId.getText();

        if (id == null || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력해야 합니다.");
            tfId.requestFocus();
            return;
        }
        String gender = tfGender.getText();

        if (gender == null || gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "성별을 입력해야 합니다.");
            tfGender.requestFocus();
            return;
        }

        if (pwd == null || pwd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호를 입력해야 합니다.");
            tfPwd.requestFocus();
            return;
        }
        
        if (pwdCheck == null || pwdCheck.isEmpty()) {
            JOptionPane.showMessageDialog(this, "비밀번호 확인을 하셔야 합니다.");
            tfPwdCheck.requestFocus();
            return;
        }
        
        if(!pwd.equals(pwdCheck)){
            JOptionPane.showMessageDialog(this, "입력하신 비밀번호가 일치하지 않습니다.");
            tfPwdCheck.requestFocus();
            return;
        }

        String jumin1 = tfJumin1.getText();
        String jumin2 = tfJumin2.getText();
        String jumin = "";

        if (jumin1.length() != 6) {
            JOptionPane.showMessageDialog(this, "주민번호 앞자리를 잘못 입력 하였습니다.");
            tfJumin1.requestFocus();
            return;
        }
        if (jumin2.length() != 7) {
            JOptionPane.showMessageDialog(this, "주민번호 뒷자리를 잘못 입력 하였습니다.");
            tfJumin1.requestFocus();
            return;
        }
        jumin = jumin1 + "-" + jumin2;

        dto.setSeller_name(name);
        dto.setSeller_gender(gender);
        dto.setSeller_id(id);
        dto.setZipcode(tfZipcode.getText());
        dto.setAddress1(tfAddress1.getText());
        dto.setAddress2(tfAddress2.getText());
        dto.setSeller_hp(tel);
        dto.setSeller_pwd(pwd);
        dto.setSeller_jumin(jumin);

        int n = dao.insert(dto);
        if (n > 0) {
            JOptionPane.showMessageDialog(this, "등록완료!");
        } else {
            JOptionPane.showMessageDialog(this, "등록실패!");
        }
        dispose();
    }

    private void idDup() throws SQLException {
        String id = tfId.getText();
        if (id == null || id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "아이디를 입력하셔야 합니다.");
            tfId.requestFocus();
            return;
        }

        
        int n = dao.login(id);
        if (n == SellerDAO.LOGIN_NOID) {
            IdCheck = true;
            tfId.setEditable(false);
        } else {
            IdCheck = false;
        }

        if (IdCheck) {
            JOptionPane.showMessageDialog(this, "사용가능한 아이디입니다.");
        } else {
            JOptionPane.showMessageDialog(this, "이미 사용중인 아이디입니다.");
        }
    }
}
